#!/bin/bash
#
# This pre-commit hook checks if any versions of clang-format
# are installed, and if so, uses the installed version to format
# the staged changes.

format=/opt/rocm/hcc/bin/clang-format

# Redirect stdout to stderr.
exec >&2

# check if clang-format is installed
if [[ ! -x $format ]]; then
    echo "$format is not installed. Pre-commit hook will not be executed."
    exit 0
fi

# Do everything from top - level
cd $(git rev-parse --show-toplevel)

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Change the copyright date at the top of any text files
for file in $(git diff-index --cached --name-only $against); do
    /usr/bin/perl -pi -e 'INIT { exit if !-f $ARGV[0] || -B $ARGV[0]; $year = (localtime)[5] + 1900 }
            s/^([*/#[:space:]]*)Copyright\s+(?:\(C\)\s*)?(\d+)(?:\s*-\s*\d+)?/qq($1Copyright $2@{[$year != $2 ? "-$year" : ""]})/ie
            if $. < 10' "$file"
done

# do the formatting
for file in $(git diff-index --cached --name-only $against | grep -E '\.h$|\.hpp$|\.cpp$|\.cl$|\.h\.in$|\.hpp\.in$|\.cpp\.in$'); do
    if [[ -e "$file" ]]; then
        sed -i -e 's/[[:space:]]*$//' "$file" # Remove whitespace at end of lines
        sed -i -e '$a\' "$file" # Add missing newline to end of file
        echo "$format $file"
        "$format" -i -style=file "$file"
    fi
done
