# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="rocblas-maintainer@amd.com"

ARG user_uid

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * tensile: python34, PyYAML
# * rocblas-test: gcc-gfortran, googletest
# * rocblas-bench: boost-devel
# * libhsakmt.so: libnuma1
RUN dnf -y update && dnf install -y \
    sudo \
    ca-certificates \
    git \
    make \
    cmake \
    gcc-c++ \
    gcc-gfortran \
    python34 \
    PyYAML \
    python3*-PyYAML \
    libcxx-devel \
    rpm-build \
    boost-devel \
    zlib-devel \
    && \
    dnf -y clean all

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G wheel --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%wheel   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd

ARG ROCBLAS_SRC_ROOT=/usr/local/src/rocBLAS

# Clone rocblas repo
# Build client dependencies and install into /usr/local (LAPACK & GTEST)
RUN mkdir -p ${ROCBLAS_SRC_ROOT} && cd ${ROCBLAS_SRC_ROOT} && \
    git clone -b develop --depth=1 https://github.com/ROCmSoftwarePlatform/rocBLAS . && \
    mkdir -p build/deps && cd build/deps && \
    cmake -DBUILD_BOOST=OFF ${ROCBLAS_SRC_ROOT}/deps && \
    make -j $(nproc) install && \
    rm -rf ${ROCBLAS_SRC_ROOT}
