# Parameters related to building rocblas
ARG base_image

FROM ${base_image}
LABEL maintainer="andrew.chapman@amd.com"

ARG user_uid

# Install dependent packages
RUN yum install -y \
    sudo \
    rock-dkms 

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd
