#pragma once

#ifdef CLIENTS_NO_FORTRAN

#define rocblas_axpy_ex_fortran rocblas_axpy_ex
#define rocblas_axpy_batched_ex_fortran rocblas_axpy_batched_ex
#define rocblas_axpy_strided_batched_ex_fortran rocblas_axpy_strided_batched_ex
#define rocblas_dot_ex_fortran rocblas_dot_ex
#define rocblas_dotc_ex_fortran rocblas_dotc_ex
#define rocblas_dot_batched_ex_fortran rocblas_dot_batched_ex
#define rocblas_dotc_batched_ex_fortran rocblas_dotc_batched_ex
#define rocblas_dot_strided_batched_ex_fortran rocblas_dot_strided_batched_ex
#define rocblas_dotc_strided_batched_ex_fortran rocblas_dotc_strided_batched_ex
#define rocblas_nrm2_ex_fortran rocblas_nrm2_ex
#define rocblas_nrm2_batched_ex_fortran rocblas_nrm2_batched_ex
#define rocblas_nrm2_strided_batched_ex_fortran rocblas_nrm2_strided_batched_ex
#define rocblas_rot_ex_fortran rocblas_rot_ex
#define rocblas_rot_batched_ex_fortran rocblas_rot_batched_ex
#define rocblas_rot_strided_batched_ex_fortran rocblas_rot_strided_batched_ex
#define rocblas_scal_ex_fortran rocblas_scal_ex
#define rocblas_scal_batched_ex_fortran rocblas_scal_batched_ex
#define rocblas_scal_strided_batched_ex_fortran rocblas_scal_strided_batched_ex
#define rocblas_gemm_ex_fortran rocblas_gemm_ex
#define rocblas_gemm_batched_ex_fortran rocblas_gemm_batched_ex
#define rocblas_gemm_strided_batched_ex_fortran rocblas_gemm_strided_batched_ex
#define rocblas_gemm_ext2_fortran rocblas_gemm_ext2
#define rocblas_trsm_ex_fortran rocblas_trsm_ex
#define rocblas_trsm_batched_ex_fortran rocblas_trsm_batched_ex
#define rocblas_trsm_strided_batched_ex_fortran rocblas_trsm_strided_batched_ex

#endif
